name: 'Email Generator Action'
description: 'Email generator action.'
branding:
  icon: 'package.svg'
  color: 'blue'

inputs:
  from_email:
    description: 'Description of the input.'
    required: true
    default: 'default value'
  to_email:
    description: 'Description of the input.'
    required: true
    default: 'default value'
  email_subject:
    description: 'Description of the input.'
    required: true
    default: 'default value'
  email_body:
    description: 'Description of the input.'
    required: true
    default: 'default value'    
  attachment_file_path:
    description: 'Description of the input.'
    required: true
    default: 'default value'
  sendgrid_api_key:
    description: 'Description of the input.'
    required: true
    default: 'default value'    

outputs:
  output_name:
    description: 'Description of the output.'
    # Add more outputs as needed

runs:
  using: 'docker'
  image: 'Dockerfile' # Path to the Dockerfile for your action

author:
  name: 'Muhammad Jamee Ghouri'
  email: 'jameeghouri@gmail.com'
  website: 'https://jamee.com'

repository:
  type: 'git'
  url: 'https://github.com/MuhammadJamee/email_generator'

# Add other optional fields as needed, such as `keywords`, `categories`, etc.
